(() => {
  const header=document.querySelector('.site-header'),menu=document.querySelector('.menu-button'),nav=document.querySelector('#site-nav'),year=document.querySelector('#year');
  const updateHeader=()=>header?.classList.toggle('scrolled',scrollY>12); updateHeader(); addEventListener('scroll',updateHeader,{passive:true});
  if(menu&&nav){menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));});nav.addEventListener('click',e=>{if(!e.target.closest('a'))return;nav.classList.remove('open');menu.setAttribute('aria-expanded','false');});document.addEventListener('click',e=>{if(nav.contains(e.target)||menu.contains(e.target))return;nav.classList.remove('open');menu.setAttribute('aria-expanded','false');});}
  if(year)year.textContent=String(new Date().getFullYear());

  const utilityStyle=document.createElement('style');utilityStyle.textContent=`.orientation-grid{grid-template-columns:repeat(auto-fit,minmax(220px,1fr))!important}.orientation-grid li:last-child{grid-column:auto!important}.clickable-card{position:relative;cursor:pointer;transition:transform 180ms ease,border-color 180ms ease,background 180ms ease}.clickable-card:hover{transform:translateY(-4px);border-color:rgba(103,212,255,.38)!important;background-color:rgba(103,212,255,.035)}.clickable-card:focus-visible{outline:2px solid var(--accent);outline-offset:4px}.clickable-card a{position:relative;z-index:2}`;document.head.appendChild(utilityStyle);
  const isExternal=link=>{try{const url=new URL(link.href,location.href);return /^https?:$/.test(url.protocol)&&url.origin!==location.origin;}catch{return false;}};
  document.querySelectorAll('a[href]').forEach(link=>{if(!isExternal(link))return;link.target='_blank';link.rel='noopener noreferrer';if(!link.title)link.title='Opens in a new tab';const label=link.getAttribute('aria-label')||link.textContent.trim();if(label&&!label.includes('opens in a new tab'))link.setAttribute('aria-label',`${label} (opens in a new tab)`);});
  document.querySelectorAll('.orientation-grid li,.branch-card,.release-card,.object-card,.source-card').forEach(card=>{const link=card.querySelector('a[href]');if(!link)return;card.classList.add('clickable-card');card.tabIndex=0;card.setAttribute('role','link');card.setAttribute('aria-label',link.getAttribute('aria-label')||link.textContent.trim());const open=()=>link.target==='_blank'?window.open(link.href,'_blank','noopener,noreferrer'):location.href=link.href;card.addEventListener('click',e=>{if(!e.target.closest('a,button,input,select,textarea,summary'))open();});card.addEventListener('keydown',e=>{if(e.target!==card||!['Enter',' '].includes(e.key))return;e.preventDefault();open();});});

  const field=document.querySelector('.field-visual');if(!field)return;
  const concepts={overview:['Interactive WCT field map','Distributed field → localized mode','Hover, focus, or tap a label to isolate each stage of the proposed confinement sequence.'],transport:['01 · Wave transport','Energy and phase remain field-distributed','Multiple propagating components carry phase and energy before persistent localized structure appears.'],band:['02 · Finite-k selection','A preferred spectral band organizes scale','Compatible wavenumbers are emphasized while unrestricted long- and short-scale growth is suppressed in the WCT proposal.'],curvature:['03 · Curvature feedback','Field geometry feeds back on localization','The selected mode changes its effective structural curvature, which reshapes and tightens the evolving pattern.'],lock:['04 · Phase locking','Coherent phase closes into a persistent mode','Compatible phases organize into the localized standing-wave structure represented by the central ψ mode.']};
  const style=document.createElement('style');style.textContent=`
    .wct-wrap{width:min(100%,560px);justify-self:end;align-self:center;display:grid;gap:16px}.field-visual.wct-field{width:100%;justify-self:auto;overflow:hidden;isolation:isolate;border-radius:46% 54% 51% 49%/52% 46% 54% 48%;background:rgba(4,10,18,.72);box-shadow:inset 0 0 120px rgba(103,212,255,.055),var(--shadow)}.field-visual.wct-field:before,.field-visual.wct-field:after{content:none!important}
    .wct-canvas,.wct-svg,.wct-vignette{position:absolute;inset:0;width:100%;height:100%}.wct-canvas{z-index:0;opacity:1;filter:saturate(1.12) contrast(1.08);transition:opacity .14s,filter .14s}.wct-vignette{z-index:1;pointer-events:none;background:radial-gradient(circle,transparent 0 29%,rgba(4,10,18,.035) 50%,rgba(4,10,18,.61) 100%)}.wct-svg{z-index:2;pointer-events:none;overflow:visible}
    .wct-flow,.wct-band,.wct-shell,.wct-core{transition:opacity .14s,transform .14s,filter .14s,stroke-width .14s}.wct-flow{fill:none;stroke:#67d4ff;stroke-width:1.15;stroke-linecap:round;stroke-dasharray:3 11;opacity:.33;vector-effect:non-scaling-stroke}.wct-band{fill:none;stroke:#8b7cff;stroke-width:.9;stroke-dasharray:2 8;opacity:.16;transform-origin:240px 240px;vector-effect:non-scaling-stroke}.wct-shell{fill:none;stroke:#b6ffda;stroke-width:1.25;opacity:.42;transform-origin:240px 240px;vector-effect:non-scaling-stroke}.wct-shell.outer{stroke-dasharray:2 7;opacity:.22}
    .wct-core{position:absolute;left:50%;top:50%;z-index:4;width:148px;transform:translate(-50%,-50%);text-align:center;pointer-events:none;text-shadow:0 0 20px #040a12,0 0 34px rgba(103,212,255,.32)}.wct-core strong{display:block;color:#b9edff;font:500 clamp(2.5rem,7vw,3.8rem)/.95 Georgia,serif}.wct-core span{display:block;margin-top:8px;color:rgba(233,240,246,.72);font-size:.61rem;font-weight:800;letter-spacing:.15em;text-transform:uppercase}
    .wct-hotspot{position:absolute;z-index:6;width:30px;height:30px;padding:0;display:grid;place-items:center;color:rgba(233,240,246,.76);border:1px solid rgba(170,201,225,.3);border-radius:50%;background:rgba(4,10,18,.7);font-size:.64rem;font-weight:800;cursor:pointer;backdrop-filter:blur(8px);transition:.12s}.wct-hotspot:hover,.wct-hotspot:focus-visible,.wct-hotspot[aria-pressed=true]{color:#06111b;background:#b6ffda;border-color:#b6ffda;transform:scale(1.08);outline:0}.wct-hotspot[data-concept=transport]{top:18%;left:13%}.wct-hotspot[data-concept=band]{top:13%;right:18%}.wct-hotspot[data-concept=curvature]{right:9%;bottom:24%}.wct-hotspot[data-concept=lock]{left:18%;bottom:14%}
    .wct-panel{display:grid;gap:11px;padding:14px;border:1px solid rgba(170,201,225,.15);border-radius:15px;background:rgba(4,10,18,.58);backdrop-filter:blur(14px)}.wct-tabs{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px}.wct-tab{min-height:40px;padding:7px 6px;color:var(--muted-2);border:1px solid rgba(170,201,225,.13);border-radius:8px;background:rgba(255,255,255,.02);font-size:.6rem;font-weight:800;letter-spacing:.05em;line-height:1.25;text-transform:uppercase;cursor:pointer;transition:.12s}.wct-tab:hover,.wct-tab:focus-visible,.wct-tab[aria-pressed=true]{color:var(--text);border-color:rgba(103,212,255,.45);background:rgba(103,212,255,.08);transform:translateY(-1px);outline:0}
    .wct-copy{min-height:88px;display:grid;align-content:start;gap:3px}.wct-kicker,.wct-title,.wct-description,.wct-note{margin:0}.wct-kicker{color:var(--accent);font-size:.61rem;font-weight:850;letter-spacing:.11em;text-transform:uppercase}.wct-title{color:var(--text);font:500 1.06rem/1.25 Georgia,serif}.wct-description{color:var(--muted-2);font-size:.75rem;line-height:1.48}.wct-note{color:rgba(113,134,154,.72);font-size:.6rem}
    .wct-field[data-active=transport] .wct-flow{opacity:.95;stroke-width:2;filter:drop-shadow(0 0 4px #67d4ff)}.wct-field[data-active=transport] .wct-band,.wct-field[data-active=transport] .wct-shell{opacity:.08}.wct-field[data-active=band] .wct-band{opacity:.9;stroke-width:1.8;filter:drop-shadow(0 0 5px #8b7cff)}.wct-field[data-active=band] .wct-flow,.wct-field[data-active=band] .wct-shell{opacity:.08}.wct-field[data-active=curvature] .wct-shell{opacity:.95;stroke-width:2.1;filter:drop-shadow(0 0 6px #b6ffda)}.wct-field[data-active=curvature] .wct-flow,.wct-field[data-active=curvature] .wct-band{opacity:.08}.wct-field[data-active=lock] .wct-core{transform:translate(-50%,-50%) scale(1.08);filter:drop-shadow(0 0 12px rgba(103,212,255,.5))}.wct-field[data-active=lock] .wct-shell{opacity:.75;stroke-width:1.8}.wct-field[data-active=lock] .wct-flow,.wct-field[data-active=lock] .wct-band{opacity:.07}.wct-field[data-active]:not([data-active=overview]) .wct-canvas{opacity:.9;filter:saturate(1.02) contrast(1.1) brightness(.92)}
    .wct-flow{animation:wctFlux 7s linear infinite}.wct-flow:nth-of-type(2n){animation-duration:9s;animation-direction:reverse}.wct-band{animation:wctBand 8s ease-in-out infinite}.wct-shell{animation:wctLock 5.5s ease-in-out infinite}@keyframes wctFlux{to{stroke-dashoffset:-84}}@keyframes wctBand{50%{transform:scale(1.025)}}@keyframes wctLock{0%,100%{transform:scale(.985)}50%{transform:scale(1.025)}}
    @media(max-width:1180px){.wct-wrap{width:min(100%,540px)}}@media(max-width:980px){.wct-wrap{justify-self:center}}@media(max-width:560px){.wct-wrap{width:100%;gap:12px}.wct-tabs{grid-template-columns:repeat(2,minmax(0,1fr))}.wct-copy{min-height:102px}.wct-panel{padding:12px}}`;
  document.head.appendChild(style);

  const wrap=document.createElement('div');wrap.className='wct-wrap';field.before(wrap);wrap.appendChild(field);field.className='field-visual wct-field';field.dataset.active='overview';field.setAttribute('aria-label','Interactive finite-band wave field converging into a localized curvature-locked mode');
  field.innerHTML=`<canvas class="wct-canvas" aria-hidden="true"></canvas><div class="wct-vignette" aria-hidden="true"></div><svg class="wct-svg" viewBox="0 0 480 480" aria-hidden="true"><path class="wct-flow" d="M-18 158C86 132 121 238 236 239"/><path class="wct-flow" d="M34 390C102 331 151 315 236 243"/><path class="wct-flow" d="M145-18C161 92 198 147 239 236"/><path class="wct-flow" d="M493 99C389 122 332 184 244 238"/><path class="wct-flow" d="M501 355C392 340 332 290 244 243"/><path class="wct-flow" d="M330 500C309 382 282 316 243 245"/><circle class="wct-band" cx="240" cy="240" r="145"/><circle class="wct-band" cx="240" cy="240" r="117"/><circle class="wct-band" cx="240" cy="240" r="92"/><path class="wct-shell outer" d="M240 160C286 158 323 195 322 239C321 286 286 321 240 321C194 322 158 286 159 240C160 195 194 161 240 160Z"/><path class="wct-shell" d="M240 187C270 184 296 208 295 239C296 270 271 296 240 294C209 297 184 270 186 240C184 208 210 186 240 187Z"/></svg><div class="wct-core" aria-hidden="true"><strong>ψ</strong><span>localized mode</span></div><button class="wct-hotspot" type="button" data-concept="transport" aria-label="Wave transport" aria-pressed="false">1</button><button class="wct-hotspot" type="button" data-concept="band" aria-label="Finite-k selection" aria-pressed="false">2</button><button class="wct-hotspot" type="button" data-concept="curvature" aria-label="Curvature feedback" aria-pressed="false">3</button><button class="wct-hotspot" type="button" data-concept="lock" aria-label="Phase locking" aria-pressed="false">4</button>`;
  const panel=document.createElement('div');panel.className='wct-panel';panel.innerHTML=`<div class="wct-tabs" aria-label="WCT field concepts"><button class="wct-tab" data-concept="transport" type="button" aria-pressed="false">Wave transport</button><button class="wct-tab" data-concept="band" type="button" aria-pressed="false">Finite-k selection</button><button class="wct-tab" data-concept="curvature" type="button" aria-pressed="false">Curvature feedback</button><button class="wct-tab" data-concept="lock" type="button" aria-pressed="false">Phase locking</button></div><div class="wct-copy" aria-live="polite"><p class="wct-kicker"></p><h2 class="wct-title"></h2><p class="wct-description"></p></div><p class="wct-note">Illustrative staged field dynamics, GPU-rendered in real time; not a numerical simulation or empirical result.</p>`;wrap.appendChild(panel);

  const controls=wrap.querySelectorAll('[data-concept]'),kicker=panel.querySelector('.wct-kicker'),title=panel.querySelector('.wct-title'),description=panel.querySelector('.wct-description');let pinned='overview',requestFieldRender=()=>{};
  const show=(name,select=false)=>{const selected=concepts[name]?name:'overview';if(select)pinned=selected;const active=select?pinned:selected;[kicker.textContent,title.textContent,description.textContent]=concepts[active];field.dataset.active=active;controls.forEach(control=>control.setAttribute('aria-pressed',String(control.dataset.concept===pinned)));requestFieldRender();};
  controls.forEach(control=>{const name=control.dataset.concept;control.addEventListener('mouseenter',()=>show(name));control.addEventListener('focus',()=>show(name));control.addEventListener('mouseleave',()=>show(pinned));control.addEventListener('blur',()=>show(pinned));control.addEventListener('click',()=>show(name,true));});show('overview');

  const canvas=field.querySelector('.wct-canvas');if(!canvas)return;const compact=matchMedia('(max-width:700px)').matches||matchMedia('(pointer:coarse)').matches,reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches,keys=['transport','band','curvature','lock'],mix={transport:1,band:0,curvature:0,lock:0};let lastMixTime=0;
  const updateMix=(time,snap=false)=>{const target={transport:0,band:0,curvature:0,lock:0},active=field.dataset.active||'overview';if(active==='overview'){const stage=3.1,transition=.36,cycle=time%(stage*4),index=Math.floor(cycle/stage)%4,phase=cycle-index*stage;if(phase<stage-transition)target[keys[index]]=1;else{const q=Math.min(1,(phase-(stage-transition))/transition),blend=q*q*(3-2*q);target[keys[index]]=1-blend;target[keys[(index+1)%4]]=blend;}}else if(target[active]!==undefined)target[active]=1;else target.transport=1;if(snap){keys.forEach(key=>mix[key]=target[key]);lastMixTime=time;return;}const dt=lastMixTime?Math.min(.08,Math.max(.001,time-lastMixTime)):1/60;lastMixTime=time;const alpha=1-Math.exp(-(active==='overview'?22:38)*dt);keys.forEach(key=>mix[key]+=(target[key]-mix[key])*alpha);};
  const resizeCanvas=gl=>{const rect=field.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,compact?1.35:1.8),width=Math.max(1,Math.round(rect.width*ratio)),height=Math.max(1,Math.round(rect.height*ratio));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;if(gl)gl.viewport(0,0,width,height);}};
  const createShader=(gl,type,source)=>{const shader=gl.createShader(type);gl.shaderSource(shader,source);gl.compileShader(shader);if(gl.getShaderParameter(shader,gl.COMPILE_STATUS))return shader;console.warn('WCT WebGL shader compile failed:',gl.getShaderInfoLog(shader));gl.deleteShader(shader);return null;};
  const createProgram=(gl,vs,fs)=>{const v=createShader(gl,gl.VERTEX_SHADER,vs),f=createShader(gl,gl.FRAGMENT_SHADER,fs);if(!v||!f)return null;const program=gl.createProgram();gl.attachShader(program,v);gl.attachShader(program,f);gl.linkProgram(program);gl.deleteShader(v);gl.deleteShader(f);if(gl.getProgramParameter(program,gl.LINK_STATUS))return program;console.warn('WCT WebGL program link failed:',gl.getProgramInfoLog(program));gl.deleteProgram(program);return null;};

  const gl=canvas.getContext('webgl',{alpha:false,antialias:false,depth:false,stencil:false,preserveDrawingBuffer:false,powerPreference:'high-performance'})||canvas.getContext('experimental-webgl',{alpha:false,antialias:false,depth:false,stencil:false,preserveDrawingBuffer:false});
  if(!gl){canvas.style.background='radial-gradient(circle at 50% 50%,rgba(70,160,205,.45),rgba(10,35,58,.72) 34%,#040a12 78%)';return;}

  const vertexSource=`attribute vec2 a_position;varying vec2 v_uv;void main(){v_uv=a_position*.5+.5;gl_Position=vec4(a_position,0.,1.);}`;
  const fragmentSource=`precision highp float;varying vec2 v_uv;uniform vec2 u_resolution;uniform float u_time;uniform vec4 u_mix;
float sat(float x){return clamp(x,0.,1.);}float tanhA(float x){float e=exp(-2.*clamp(x,-8.,8.));return(1.-e)/(1.+e);}
float tf(vec2 p,float t){float s=0.;float d=.22;vec2 q=vec2(cos(d),sin(d)),n=vec2(-q.y,q.x);s+=sin(13.4*dot(p,q)-t*2.65)*(.48+.52*exp(-1.85*pow(dot(p,n),2.)));d=2.3143951024;q=vec2(cos(d),sin(d));n=vec2(-q.y,q.x);s+=sin(13.4*dot(p,q)-t*2.96+1.72)*(.48+.52*exp(-1.85*pow(dot(p,n),2.)));d=4.4087902048;q=vec2(cos(d),sin(d));n=vec2(-q.y,q.x);s+=sin(13.4*dot(p,q)-t*3.27+3.44)*(.48+.52*exp(-1.85*pow(dot(p,n),2.)));s/=3.;float c=.48*sin(9.8*(p.x+.72*p.y)+t*1.82)+.42*cos(18.6*(.67*p.x-p.y)-t*2.28);return s+.38*c;}
float bf(vec2 p,float r,float t){float k=15.4,s=0.,d=.12;s+=cos(k*dot(p,vec2(cos(d),sin(d)))+.58*sin(t*.52));d=.9053981634;s+=cos(k*dot(p,vec2(cos(d),sin(d)))+.58*sin(t*.52+1.17));d=1.6907963268;s+=cos(k*dot(p,vec2(cos(d),sin(d)))+.58*sin(t*.52+2.34));d=2.4761944902;s+=cos(k*dot(p,vec2(cos(d),sin(d)))+.58*sin(t*.52+3.51));return s*.25+.22*cos(k*r-t*.44);}
float cf(float r,float a,float t){float w=r+.13*r*r+.035*r*r*r,aw=1.22*sin(2.*a-t*.42)*(1.-.34*r)+.36*sin(3.*a+t*.31)*r;return sin(15.8*w-t*1.28+aw)+.38*cos(21.6*w+3.*a+t*.72);}float lf(float r,float a,float t){float s=sin(16.8*r+1.08*sin(2.*a))+.34*cos(23.4*r+3.*a);return s*(.88+.12*sin(t*1.18));}
void main(){vec2 p=v_uv*2.-1.;p.y=-p.y;p.x*=u_resolution.x/max(u_resolution.y,1.);float r=length(p),a=atan(p.y,p.x),fade=sat((1.42-r)*2.45),ce=exp(-1.45*r*r),le=exp(-3.05*r*r);float tr=u_mix.x>.001?tf(p,u_time):0.,ba=u_mix.y>.001?bf(p,r,u_time):0.,cu=u_mix.z>.001?cf(r,a,u_time):0.,lo=u_mix.w>.001?lf(r,a,u_time):0.;float f=u_mix.x*1.05*tr+u_mix.y*1.34*ba+u_mix.z*1.46*ce*cu+u_mix.w*1.72*le*lo;float st=u_mix.x*.05+u_mix.y*.12+u_mix.z*.55*ce+u_mix.w*.95*le,crest=.5+.5*tanhA(f*1.12),amp=min(1.,abs(f)*.72+st*.24)*fade,nw=u_mix.x*.035+u_mix.y*.07+u_mix.z*.12*ce+u_mix.w*.2*le,node=exp(-26.*abs(f))*nw,pulse=1.+u_mix.x*.025*sin(u_time*1.9-r*5.5)+u_mix.y*.018*sin(u_time*.78)+u_mix.z*.035*sin(u_time*1.04-r*3.1)+u_mix.w*.055*sin(u_time*1.18),g=amp*pulse;vec3 col=vec3(4.+(90.+44.*(1.-crest))*g+88.*node,10.+(168.+50.*crest)*g+148.*node,18.+(222.+30.*crest)*g+135.*node)/255.;gl_FragColor=vec4(col,1.);}`;
  const program=createProgram(gl,vertexSource,fragmentSource);if(!program){canvas.style.background='#040a12';return;}const pos=gl.getAttribLocation(program,'a_position'),timeLoc=gl.getUniformLocation(program,'u_time'),mixLoc=gl.getUniformLocation(program,'u_mix'),resLoc=gl.getUniformLocation(program,'u_resolution'),buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);gl.useProgram(program);gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,2,gl.FLOAT,false,0,0);gl.disable(gl.DEPTH_TEST);gl.disable(gl.BLEND);

  const start=performance.now();let frame=0,visible=true,running=false,contextLost=false;
  const render=(time,snap=false)=>{if(contextLost)return;updateMix(time,snap||reducedMotion);resizeCanvas(gl);gl.useProgram(program);gl.uniform1f(timeLoc,time);gl.uniform4f(mixLoc,mix.transport,mix.band,mix.curvature,mix.lock);gl.uniform2f(resLoc,canvas.width,canvas.height);gl.drawArrays(gl.TRIANGLES,0,3);};
  requestFieldRender=()=>render((performance.now()-start)/1000,reducedMotion);
  const animate=timestamp=>{if(!visible||contextLost){running=false;return;}render((timestamp-start)/1000);frame=requestAnimationFrame(animate);};const play=()=>{if(running||!visible||reducedMotion||contextLost)return;running=true;frame=requestAnimationFrame(animate);};
  canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();contextLost=true;cancelAnimationFrame(frame);running=false;});canvas.addEventListener('webglcontextrestored',()=>location.reload());
  resizeCanvas(gl);render(0,true);if('ResizeObserver'in window)new ResizeObserver(()=>{resizeCanvas(gl);requestFieldRender();}).observe(field);else addEventListener('resize',()=>{resizeCanvas(gl);requestFieldRender();},{passive:true});if('IntersectionObserver'in window)new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;if(visible){requestFieldRender();play();}else{cancelAnimationFrame(frame);running=false;}},{rootMargin:'120px'}).observe(field);play();
})();
