window.overlapRelationshipByUrl = Object.assign(window.overlapRelationshipByUrl || {}, {
  "https://openai.com/index/model-misalignment-reporting-framework/": "EMPIRICAL CONVERGENCE",
  "https://www.anthropic.com/research/alignment-assessment-cybersecurity-incidents": "EMPIRICAL CONVERGENCE",
  "https://metr.org/agent-incidents/": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2605.17830": "INDEPENDENT CONVERGENCE",
  "https://arxiv.org/abs/2605.15338": "INDEPENDENT CONVERGENCE",
  "https://alignment.anthropic.com/2026/agentic-misalignment-summer-2026/": "EMPIRICAL CONVERGENCE",
  "https://deepmind.google/blog/securing-the-future-of-ai-agents/": "INSTITUTIONAL RESPONSE",
  "https://arxiv.org/abs/2606.24322": "INDEPENDENT CONVERGENCE",
  "https://apolloresearch.ai/science/metagaming-matters-for-training-evaluation-and-oversight": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2607.18966": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2603.27148": "INDEPENDENT CONVERGENCE",
  "https://arxiv.org/abs/2606.23075": "INDEPENDENT CONVERGENCE",
  "https://arxiv.org/abs/2603.03824": "EMPIRICAL CONVERGENCE",
  "https://openai.com/index/how-we-monitor-internal-coding-agents-misalignment/": "INSTITUTIONAL RESPONSE",
  "https://arxiv.org/abs/2602.22303": "INSTITUTIONAL RESPONSE",
  "https://arxiv.org/abs/2605.30322": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2603.01608": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2605.27681": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2607.24758": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2605.10481": "INDEPENDENT CONVERGENCE",
  "https://alignment.anthropic.com/2026/automated-alignment-researchers/": "INSTITUTIONAL RESPONSE",
  "https://deepmind.google/blog/investing-in-multi-agent-ai-safety-research/": "INSTITUTIONAL RESPONSE",
  "https://arxiv.org/abs/2603.11768": "INDEPENDENT CONVERGENCE",
  "https://deepmind.google/blog/strengthening-our-frontier-safety-framework/": "INSTITUTIONAL RESPONSE",
  "https://arxiv.org/abs/2606.15385": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2601.04170": "INDEPENDENT CONVERGENCE",
  "https://arxiv.org/abs/2502.19559": "STRUCTURAL OVERLAP",
  "https://openai.com/index/reasoning-models-chain-of-thought-controllability/": "INSTITUTIONAL RESPONSE",
  "https://www.apolloresearch.ai/science/we-need-3rd-party-training-run-assessments": "INSTITUTIONAL RESPONSE",
  "https://arxiv.org/abs/2605.11026": "INDEPENDENT CONVERGENCE",
  "https://arxiv.org/abs/2603.15255": "STRUCTURAL OVERLAP",
  "https://arxiv.org/abs/2511.18397": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2608.26195": "INDEPENDENT CONVERGENCE",
  "https://arxiv.org/abs/2604.15149": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2605.02964": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2508.17511": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2502.02649": "STRUCTURAL OVERLAP",
  "https://www.media.mit.edu/groups/nanda/overview/": "STRUCTURAL OVERLAP",
  "https://www.tdcommons.org/2026.html": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2609.13951": "INDEPENDENT CONVERGENCE",
  "https://arxiv.org/abs/2609.18883": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2609.11668": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2609.12080": "INDEPENDENT CONVERGENCE",
  "https://arxiv.org/abs/2609.17092": "INDEPENDENT CONVERGENCE",
  "https://arxiv.org/abs/2609.03259": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2609.21314": "INDEPENDENT CONVERGENCE"
});

window.overlapRelationshipDefinitions = {
  "DIRECT ADOPTION": "Explicit citation, implementation, use, testing, or discussion of WCT / Recursive AI Drift.",
  "INDEPENDENT CONVERGENCE": "Later independent work develops a closely corresponding concept, mechanism, or systems model.",
  "EMPIRICAL CONVERGENCE": "External experiments, evaluations, disclosures, or incidents directly observe the same class of behavior.",
  "INSTITUTIONAL RESPONSE": "A research lab or safety program introduces monitoring, containment, governance, or mitigation aimed at the same failure class.",
  "STRUCTURAL OVERLAP": "A technically related comparison with meaningful structural correspondence.",
  "PRIOR ART / CONTROL": "Earlier work retained as a chronology, novelty, or baseline control."
};