window.overlapRelationshipByUrl = Object.assign(window.overlapRelationshipByUrl || {}, {
  "https://openai.com/index/model-misalignment-reporting-framework/": "EMPIRICAL CONVERGENCE",
  "https://www.anthropic.com/research/alignment-assessment-cybersecurity-incidents": "EMPIRICAL CONVERGENCE",
  "https://metr.org/agent-incidents/": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2605.17830": "POST-DATE CONVERGENCE",
  "https://arxiv.org/abs/2605.15338": "POST-DATE CONVERGENCE",
  "https://alignment.anthropic.com/2026/agentic-misalignment-summer-2026/": "EMPIRICAL CONVERGENCE",
  "https://deepmind.google/blog/securing-the-future-of-ai-agents/": "INSTITUTIONAL RESPONSE",
  "https://arxiv.org/abs/2606.24322": "POST-DATE CONVERGENCE",
  "https://apolloresearch.ai/science/metagaming-matters-for-training-evaluation-and-oversight": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2607.18966": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2603.27148": "POST-DATE CONVERGENCE",
  "https://arxiv.org/abs/2606.23075": "POST-DATE CONVERGENCE",
  "https://arxiv.org/abs/2603.03824": "EMPIRICAL CONVERGENCE",
  "https://openai.com/index/how-we-monitor-internal-coding-agents-misalignment/": "INSTITUTIONAL RESPONSE",
  "https://arxiv.org/abs/2602.22303": "INSTITUTIONAL RESPONSE",
  "https://arxiv.org/abs/2605.30322": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2603.01608": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2605.27681": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2607.24758": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2605.10481": "POST-DATE CONVERGENCE",
  "https://alignment.anthropic.com/2026/automated-alignment-researchers/": "INSTITUTIONAL RESPONSE",
  "https://deepmind.google/blog/investing-in-multi-agent-ai-safety-research/": "INSTITUTIONAL RESPONSE",
  "https://arxiv.org/abs/2603.11768": "POST-DATE CONVERGENCE",
  "https://deepmind.google/blog/strengthening-our-frontier-safety-framework/": "INSTITUTIONAL RESPONSE",
  "https://arxiv.org/abs/2606.15385": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2601.04170": "POST-DATE CONVERGENCE",
  "https://arxiv.org/abs/2502.19559": "STRUCTURAL OVERLAP",
  "https://openai.com/index/reasoning-models-chain-of-thought-controllability/": "INSTITUTIONAL RESPONSE",
  "https://www.apolloresearch.ai/science/we-need-3rd-party-training-run-assessments": "INSTITUTIONAL RESPONSE",
  "https://arxiv.org/abs/2605.11026": "POST-DATE CONVERGENCE",
  "https://arxiv.org/abs/2603.15255": "STRUCTURAL OVERLAP",
  "https://arxiv.org/abs/2511.18397": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2608.26195": "POST-DATE CONVERGENCE",
  "https://arxiv.org/abs/2604.15149": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2605.02964": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2508.17511": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2502.02649": "STRUCTURAL OVERLAP",
  "https://www.media.mit.edu/groups/nanda/overview/": "STRUCTURAL OVERLAP",
  "https://www.tdcommons.org/2026.html": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2609.13951": "POST-DATE CONVERGENCE",
  "https://arxiv.org/abs/2609.18883": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2609.11668": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2609.12080": "POST-DATE CONVERGENCE",
  "https://arxiv.org/abs/2609.17092": "POST-DATE CONVERGENCE",
  "https://arxiv.org/abs/2609.03259": "EMPIRICAL CONVERGENCE",
  "https://arxiv.org/abs/2609.21314": "POST-DATE CONVERGENCE",
  "https://doi.org/10.1140/epjd/s10053-026-01252-6": "POST-DATE CONVERGENCE",
  "https://doi.org/10.1007/s11071-026-13056-9": "POST-DATE CONVERGENCE",
  "https://arxiv.org/abs/2609.24327": "POST-DATE CONVERGENCE",
  "https://arxiv.org/abs/2609.24063": "STRUCTURAL OVERLAP",
  "https://arxiv.org/abs/2609.19348": "STRUCTURAL OVERLAP",
  "https://arxiv.org/abs/2609.02374": "STRUCTURAL OVERLAP",
  "https://arxiv.org/abs/2609.11577": "STRUCTURAL OVERLAP",

  "https://arxiv.org/abs/2507.02223": "EMPIRICAL CONVERGENCE",
  "https://doi.org/10.1038/s41586-026-10825-9": "EMPIRICAL CONVERGENCE",
  "https://doi.org/10.1038/s41377-025-02147-8": "EMPIRICAL CONVERGENCE",
  "https://doi.org/10.1038/s41566-025-01840-9": "EMPIRICAL CONVERGENCE",
  "https://doi.org/10.1038/s41586-026-10292-2": "EMPIRICAL CONVERGENCE",
  "https://doi.org/10.1016/j.optlastec.2026.115112": "EMPIRICAL CONVERGENCE",
  "https://doi.org/10.1364/CLEO_FS.2026.FW1H.3": "EMPIRICAL CONVERGENCE",
  "https://doi.org/10.1364/CLEO_FS.2026.FW1H.7": "EMPIRICAL CONVERGENCE",
  "https://doi.org/10.1103/v6pf-rgv8": "POST-DATE CONVERGENCE",
  "https://arxiv.org/abs/2609.31267": "POST-DATE CONVERGENCE",
  "https://iramis.cea.fr/en/2026/07/first-all-optical-photonic-time-crystal-opens-a-new-route-to-controlling-light/": "INSTITUTIONAL RESPONSE",
  "https://www.southampton.ac.uk/study/postgraduate-research/projects/photonic-time-crystals-timetronics": "INSTITUTIONAL RESPONSE"
});

window.overlapRelationshipDefinitions = {
  "DIRECT ADOPTION": "Explicit citation, implementation, use, testing, or discussion of WCT / Recursive AI Drift.",
  "POST-DATE CONVERGENCE": "A later external work develops a closely corresponding concept, mechanism, or systems model.",
  "EMPIRICAL CONVERGENCE": "Experiments, evaluations, datasets, disclosures, or incidents directly observe the same class of behavior.",
  "INSTITUTIONAL RESPONSE": "A lab, university, company, government, or funded program establishes sustained research, monitoring, containment, or engineering around the same problem class.",
  "STRUCTURAL OVERLAP": "A technically related comparison with meaningful structural correspondence.",
  "PRIOR ART / CONTROL": "Earlier work retained as a chronology, novelty, or baseline control."
};